# Generated by Django 5.2 on 2025-04-27 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_class', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Location Category',
                'verbose_name_plural': 'Location Categories',
            },
        ),
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('floor_level', models.IntegerField(default=0)),
                ('is_accessible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='location.locationcategory')),
            ],
            options={
                'verbose_name': 'Campus Location',
                'verbose_name_plural': 'Campus Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='location.campuslocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favorite Location',
                'verbose_name_plural': 'User Favorite Locations',
            },
        ),
        migrations.AddIndex(
            model_name='campuslocation',
            index=models.Index(fields=['longitude', 'latitude'], name='location_ca_longitu_1ab728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritelocation',
            unique_together={('user', 'location')},
        ),
    ]
