# Generated by Django 5.2 on 2025-05-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_deleted_at'),
        ('chatbot', '0002_recreate_conversation'),
    ]

    operations = [
    ]
