# Generated by Django 5.2 on 2025-04-12 08:35

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_university_email_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university_email',
            field=models.EmailField(default='example@default.com', max_length=254, unique=True, verbose_name='university email'),
        ),
    ]
