# Generated by Django 5.2 on 2025-04-12 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_pinned', '-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='authentication.department'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['department'], name='authenticat_departm_b46ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at'], name='authenticat_created_f1e681_idx'),
        ),
    ]
