# Generated by Django 5.2 on 2025-04-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_answer_question_alter_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weighted_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='authentication.question'),
        ),
    ]
